version: '3.8'

services:
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - '5173:5173' # Mapowanie portu dla Vite
        volumes:
            - ./client:/app
            - node_modules:/app/node_modules
        networks:
            - app-network

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '3000:3000' # Mapowanie portu dla Express.js
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    node_modules:
